import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import Navbar from '../components/Navbar';
import UploadZone from '../components/UploadZone';
import { useApp } from '../context/AppContext';
import { BrdDocument } from '../types';

type Stage = 1 | 2 | 3;

const SAMPLES = [
  { title: 'Fintech OTP Validation', text: 'Customer authentication flow, add dual SMS and Email verification, enforce 300 second lockout after 3 failed OTP attempts.', cat: 'Fintech' },
  { title: 'CRM Syncing Logs',       text: 'SAP synchronization engine, daily batch files to SAP, retry three times on connection failure, incremental logs.', cat: 'CRM' },
  { title: 'Policy Compliance Specs', text: 'GDPR audit trail data retention clause, user must opt in manually, purge customer record within 30 days of request.', cat: 'Compliance' },
];

function parseBrdFromMarkdown(projectName: string, markdown: string): BrdDocument {
  const objectives: string[] = [];
  const functionalRequirements: BrdDocument['functionalRequirements'] = [];
  const userStories: BrdDocument['userStories'] = [];

  const objMatch = markdown.match(/(?:objectives?|goals?)[^\n]*\n((?:[\s\S]*?))(?=\n#{1,3}|$)/i);
  if (objMatch) {
    const bullets = objMatch[1].match(/^[-*\d.]+\s+(.+)$/gm);
    if (bullets) objectives.push(...bullets.slice(0, 5).map(b => b.replace(/^[-*\d.]+\s+/, '')));
  }

  const frMatch = markdown.match(/functional requirements?[^\n]*\n((?:[\s\S]*?))(?=\n#{1,3}|$)/i);
  if (frMatch) {
    const bullets = frMatch[1].match(/^[-*\d.]+\s+(.+)$/gm);
    if (bullets) {
      bullets.slice(0, 4).forEach((b, i) => {
        const txt = b.replace(/^[-*\d.]+\s+/, '');
        functionalRequirements.push({ id: `REQ-${i + 1}.0`, title: txt.slice(0, 60), description: txt, status: 'Validated' });
      });
    }
  }

  const summaryMatch = markdown.match(/executive summary[^\n]*\n+([^\n#][^\n]+(?:\n[^\n#][^\n]+)*)/i);
  const executiveSummary = summaryMatch ? summaryMatch[1].trim() : `BRD for ${projectName} generated by Genie.`;

  const flowchartSvg = `<svg viewBox="0 0 400 160" fill="none"><rect x="10" y="40" width="80" height="40" fill="#6d5ef5" fill-opacity="0.1" stroke="var(--color-accent-gold)" stroke-width="1.5"/><text x="50" y="65" fill="#fff" font-size="9" font-weight="bold" text-anchor="middle">Input</text><path d="M 90 60 L 140 60" stroke="var(--color-accent-gold)" stroke-width="1.5" stroke-dasharray="3,3"/><rect x="150" y="40" width="100" height="40" fill="#016678" fill-opacity="0.1" stroke="var(--color-accent-gold)" stroke-width="1.5"/><text x="200" y="65" fill="#fff" font-size="9" font-weight="bold" text-anchor="middle">Processing</text><path d="M 250 60 L 300 60" stroke="var(--color-accent-gold)" stroke-width="1.5"/><rect x="310" y="40" width="80" height="40" fill="#14532d" fill-opacity="0.1" stroke="var(--color-accent-gold)" stroke-opacity="0.7" stroke-width="1.5"/><text x="350" y="65" fill="#fff" font-size="9" font-weight="bold" text-anchor="middle">Output</text></svg>`;

  return {
    projectName,
    executiveSummary,
    objectives: objectives.length ? objectives : ['Define initial functional scope.', 'Formulate integration architecture.'],
    functionalRequirements: functionalRequirements.length ? functionalRequirements : [
      { id: 'REQ-1.0', title: 'Core System Processing', description: markdown.slice(0, 200), status: 'Validated' },
    ],
    flowchartSvg,
    userStories: userStories.length ? userStories : [{ actor: 'End User', goal: 'Complete the primary workflow', outcome: 'Task completes successfully.' }],
    suggestedImprovements: [
      { id: 'imp1', text: 'Add detailed error handling and fallback states', applied: false },
      { id: 'imp2', text: 'Specify SLA thresholds for peak load scenarios', applied: false },
    ],
  };
}

const LANGS = ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali', 'Marathi', 'Kannada', 'Gujarati', 'Malayalam'];

export default function WorkspaceView() {
  const { navigate, addProject, addToast } = useApp();

  const [projectName, setProjectName] = useState('Fintech Micro-Lending Portal');
  const [stakeholders, setStakeholders] = useState('Product Management, Compliance Team, Security Ops');
  const [lang, setLang] = useState('English');
  const [stage, setStage] = useState<Stage>(2);
  const [transcribeP, setTranscribeP] = useState(100);
  const [analyzeP, setAnalyzeP] = useState(65);
  const [runState, setRunState] = useState<'idle' | 'running' | 'done'>('idle');
  const [generatedBrd, setGeneratedBrd] = useState<BrdDocument | null>(null);
  const [backendState, setBackendState] = useState<Record<string, unknown> | null>(null);
  const [clarifyQuestions, setClarifyQuestions] = useState<string[]>([]);
  const [clarifyAnswers, setClarifyAnswers] = useState<string[]>([]);
  const [awaitingClarify, setAwaitingClarify] = useState(false);

  const [chat, setChat] = useState<{ sender: 'ai' | 'user'; text: string; time: string }[]>([{
    sender: 'ai',
    text: "I've processed your transcript snippet and detected a potential conflict around \"User Permissions\". Should we implement standard MFA via SMS, or configure OAuth2 tokens with full RBAC?",
    time: '12:04 PM',
  }]);
  const [chatInput, setChatInput] = useState('');

  const mountedRef = useRef(true);
  useEffect(() => { mountedRef.current = true; return () => { mountedRef.current = false; }; }, []);

  const animateProgress = (setter: (v: number) => void, step: number, interval: number) =>
    new Promise<void>(res => {
      let p = 0;
      const iv = setInterval(() => {
        if (!mountedRef.current) { clearInterval(iv); res(); return; }
        p += step; setter(Math.min(p, 100));
        if (p >= 100) { clearInterval(iv); res(); }
      }, interval);
    });

  const finalizeBrd = (state: Record<string, unknown>, name: string) => {
    const markdown = (state.final_brd as string) || (state.brd_draft as string) || '';
    setGeneratedBrd(parseBrdFromMarkdown(name, markdown));
    setBackendState(state);
    setStage(3);
    setRunState('done');
    setChat(prev => [...prev, {
      sender: 'ai',
      text: `BRD for "${name}" generated successfully! I've structured ${markdown.split('\n').filter(l => l.startsWith('-') || l.startsWith('*')).length} requirements across multiple compliance categories. Ready to compile the v1.0 draft?`,
      time: 'Just now',
    }]);
  };

  const runPipeline = async (name: string, rawText: string, file?: File) => {
    const clean = name.replace(/\.[^/.]+$/, '') + ' Draft';
    if (!mountedRef.current) return;
    setProjectName(clean);
    setRunState('running');
    setStage(1); setTranscribeP(0); setAnalyzeP(0);
    setAwaitingClarify(false); setClarifyQuestions([]); setClarifyAnswers([]);

    await animateProgress(setTranscribeP, 12, 100);
    if (!mountedRef.current) return;
    setStage(2);

    try {
      const formData = new FormData();
      formData.append('language', lang);
      if (file) {
        formData.append('file', file);
      } else {
        formData.append('raw_text', rawText);
      }

      const progressStop = { stop: false };
      const progressPromise = new Promise<void>(res => {
        let p = analyzeP;
        const iv = setInterval(() => {
          if (progressStop.stop || !mountedRef.current) { clearInterval(iv); res(); return; }
          p = Math.min(p + 3, 90);
          setAnalyzeP(p);
        }, 200);
      });

      const response = await fetch('/api/start', { method: 'POST', body: formData });
      progressStop.stop = true;
      setAnalyzeP(100);
      await new Promise(r => setTimeout(r, 200));

      if (!mountedRef.current) return;

      if (!response.ok) {
        const err = await response.json().catch(() => ({ detail: 'Unknown error' }));
        addToast(`Backend error: ${err.detail}`, 'error');
        setRunState('idle');
        return;
      }

      const state = await response.json();
      const questions: string[] = state.questions || [];

      if (questions.length > 0 && !(state.answers?.length)) {
        setClarifyQuestions(questions);
        setClarifyAnswers(questions.map(() => ''));
        setBackendState(state);
        setAwaitingClarify(true);
        setRunState('running');
        setChat(prev => [...prev, {
          sender: 'ai',
          text: `I detected ${questions.length} ambiguities in your requirements. Please answer the clarification questions to continue.`,
          time: 'Just now',
        }]);
      } else {
        finalizeBrd(state, clean);
      }
    } catch (e) {
      addToast('Failed to connect to backend. Is the FastAPI server running on port 8000?', 'error');
      setRunState('idle');
    }
  };

  const handleClarifySubmit = async () => {
    if (!backendState) return;
    setAwaitingClarify(false);
    setStage(2); setAnalyzeP(0);
    try {
      let p = 0;
      const iv = setInterval(() => { p = Math.min(p + 2, 88); setAnalyzeP(p); }, 200);
      const response = await fetch('/api/clarify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ state: backendState, answers: clarifyAnswers }),
      });
      clearInterval(iv);
      setAnalyzeP(100);
      if (!mountedRef.current) return;
      if (!response.ok) {
        const err = await response.json().catch(() => ({ detail: 'Unknown error' }));
        addToast(`Clarify error: ${err.detail}`, 'error');
        setRunState('idle');
        return;
      }
      const state = await response.json();
      finalizeBrd(state, projectName);
    } catch {
      addToast('Clarification request failed. Check backend connection.', 'error');
      setRunState('idle');
    }
  };

  const handleSample = (s: typeof SAMPLES[0]) => runPipeline(s.title, s.text);
  const handleUpload = (f: File, text: string) => {
    addToast(`Loaded ${f.name}. Sending to backend…`, 'info');
    const isAudio = /\.(mp3|wav|m4a)$/i.test(f.name);
    runPipeline(f.name, text, isAudio ? f : undefined);
  };
  const handleUploadError = (msg: string) => addToast(msg, 'error');

  const handleSendChat = async (text: string) => {
    setChatInput('');
    setChat(prev => [...prev, { sender: 'user', text, time: 'Just now' }]);

    if (backendState && runState === 'done') {
      try {
        const response = await fetch('/api/clarify', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ state: backendState, answers: [text] }),
        });
        if (response.ok) {
          const state = await response.json();
          setBackendState(state);
          const markdown = (state.final_brd as string) || (state.brd_draft as string) || '';
          if (markdown) setGeneratedBrd(parseBrdFromMarkdown(projectName, markdown));
          setChat(prev => [...prev, { sender: 'ai', text: `Incorporated: "${text}". The document has been updated.`, time: 'Just now' }]);
          return;
        }
      } catch {
      }
    }

    setChat(prev => [...prev, { sender: 'ai', text: `Noted: "${text}". Generate a BRD first to apply refinements via the backend.`, time: 'Just now' }]);
  };

  const handleCompile = () => {
    if (!generatedBrd) return;
    const id = addProject({ name: projectName, status: 'AI Generated', language: lang, category: projectName, icon: 'description' }, generatedBrd);
    addToast(`"${projectName}" compiled successfully! Opening editor…`, 'success');
    setTimeout(() => navigate('document'), 1300);
  };

  return (
    <div className="min-h-screen bg-bg-cream dark:bg-black text-primary dark:text-white pb-24 font-sans transition-colors duration-300">
      <Navbar active="workspace" />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-12">
        <motion.header initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-8">
          <span className="text-[10px] uppercase tracking-[0.22em] text-accent-gold font-bold font-mono">Precision Workshop</span>
          <h1 className="font-display text-3xl font-semibold text-primary dark:text-white mt-1 mb-2 tracking-tight">BRD Compiler Desk</h1>
          <p className="font-sans text-slate-655 dark:text-zinc-400 italic font-light">Transcribe recordings, run compliance workflows, and compile publication-grade specifications.</p>
        </motion.header>

        <motion.section initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.5, delay: 0.1 }}
          className="bg-surface dark:bg-[#111111] border border-black/5 dark:border-white/10 p-6 shadow-sm mb-8"
        >
          <div className="flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="flex items-center gap-2">
              <div className={`h-2 w-2 rounded-full ${runState === 'running' ? 'bg-accent-gold animate-pulse' : 'bg-emerald-500'}`} />
              <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-accent-gold font-mono">
                {runState === 'idle' ? 'PIPELINE READY' : runState === 'running' ? 'PIPELINE ACTIVE' : 'PIPELINE COMPLETE'}
              </span>
            </div>

            <div className="flex flex-wrap items-center gap-4 sm:gap-8 font-mono">
              {([
                { n: 1, label: 'Transcription', done: stage >= 2, active: stage === 1, pct: transcribeP },
                { n: 2, label: 'Analysing',     done: stage >= 3, active: stage === 2, pct: analyzeP   },
                { n: 3, label: 'Writing',        done: false,       active: stage === 3, pct: 100        },
              ] as const).map(({ n, label, done, active, pct }, i) => (
                <React.Fragment key={n}>
                  {i > 0 && <div className="h-px w-8 bg-black/5 dark:bg-white/5" />}
                  <div className="flex items-center gap-3">
                    <div className={`h-8 w-8 flex items-center justify-center font-bold text-xs border transition-colors ${
                      done   ? 'bg-accent-gold text-white border-accent-gold' :
                      active ? 'bg-primary dark:bg-zinc-800 text-white border-primary dark:border-zinc-600 animate-pulse' :
                               'bg-bg-cream dark:bg-zinc-900 text-slate-450 border-black/5 dark:border-white/5'
                    }`}>
                      {done ? <span className="material-symbols-outlined text-sm" style={{ fontVariationSettings: "'FILL' 1" }}>done</span> : n}
                    </div>
                    <div>
                      <p className="font-sans font-semibold text-xs text-primary dark:text-white leading-tight">{label}</p>
                      <span className="text-[9px] uppercase font-bold tracking-wider text-slate-450 dark:text-zinc-500 block">
                        {done ? 'Complete' : active ? `${pct}%` : 'Waiting'}
                      </span>
                    </div>
                  </div>
                </React.Fragment>
              ))}
            </div>
          </div>

          {runState === 'running' && (
            <div className="w-full bg-black/5 dark:bg-white/5 h-[3px] overflow-hidden mt-5">
              <motion.div className="bg-accent-gold h-full" animate={{ width: `${stage === 1 ? transcribeP : analyzeP}%` }} transition={{ duration: 0.2 }} />
            </div>
          )}
        </motion.section>

        {awaitingClarify && (
          <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            className="bg-amber-50 dark:bg-amber-950/30 border border-amber-300 dark:border-amber-700 p-6 mb-8 space-y-4"
          >
            <h3 className="font-sans font-bold text-sm text-amber-800 dark:text-amber-400 flex items-center gap-2">
              <span className="material-symbols-outlined text-base" style={{ fontVariationSettings: "'FILL' 1" }}>help</span>
              Genie needs clarification ({clarifyQuestions.length} questions)
            </h3>
            {clarifyQuestions.map((q, i) => (
              <div key={i}>
                <label className="block text-xs font-bold text-slate-700 dark:text-zinc-300 mb-1">Q{i + 1}: {q}</label>
                <input
                  type="text"
                  value={clarifyAnswers[i] ?? ''}
                  onChange={e => setClarifyAnswers(prev => { const a = [...prev]; a[i] = e.target.value; return a; })}
                  placeholder="Your answer…"
                  className="w-full bg-white dark:bg-zinc-900 border border-amber-300 dark:border-amber-700 focus:border-accent-gold px-4 py-2 text-xs outline-none font-sans text-primary dark:text-white"
                />
              </div>
            ))}
            <button onClick={handleClarifySubmit}
              className="bg-amber-600 hover:bg-amber-700 text-white font-bold py-2.5 px-6 text-xs uppercase tracking-widest transition-all active:scale-95"
            >
              Submit Answers &amp; Generate BRD ➜
            </button>
          </motion.section>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
          <div className="lg:col-span-8 space-y-8">

            <div className="bg-surface dark:bg-[#111111] border border-black/5 dark:border-white/10 p-6 shadow-sm">
              <h3 className="font-sans text-lg font-semibold text-primary dark:text-white border-b border-black/5 dark:border-white/10 pb-3 mb-6">Portfolio Parameters</h3>
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {[
                    { label: 'Manuscript Name',  val: projectName,   set: setProjectName,  ph: 'CRM-to-SAP Integration v2' },
                    { label: 'Core Stakeholders', val: stakeholders,  set: setStakeholders, ph: 'Product, Security Ops, Sales' },
                  ].map(({ label, val, set, ph }) => (
                    <div key={label}>
                      <label className="block text-slate-655 dark:text-zinc-400 text-[10px] font-bold uppercase tracking-widest mb-1.5">{label}</label>
                      <input value={val} onChange={e => set(e.target.value)} placeholder={ph} type="text"
                        className="w-full bg-surface dark:bg-zinc-900 border border-black/10 dark:border-white/10 focus:border-accent-gold focus:ring-0 px-4 py-2.5 text-xs outline-none text-primary dark:text-white transition-all font-sans font-semibold rounded-none"
                      />
                    </div>
                  ))}
                </div>

                <div>
                  <label className="block text-slate-655 dark:text-zinc-400 text-[10px] font-bold uppercase tracking-widest mb-2">Output Language (Indian Region Presets)</label>
                  <div className="flex flex-wrap gap-2">
                    {LANGS.map(l => (
                      <button key={l} type="button" onClick={() => setLang(l)}
                        className={`px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-all rounded-full ${
                          lang === l
                            ? 'bg-primary dark:bg-accent-purple text-white shadow-md scale-105'
                            : 'bg-surface dark:bg-zinc-900 border border-black/5 dark:border-white/10 text-slate-500 hover:text-primary dark:hover:text-white hover:border-accent-gold'
                        }`}
                      >{l}</button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-surface dark:bg-[#111111] border border-black/5 dark:border-white/10 p-6 shadow-sm">
              <h3 className="font-sans text-lg font-semibold text-primary dark:text-white border-b border-black/5 dark:border-white/10 pb-3 mb-6">Import Transcripts or Voice Memos</h3>
              <div className="mb-6">
                <UploadZone onFileAccepted={handleUpload} onError={handleUploadError} />
              </div>
              <div>
                <span className="text-[10px] font-bold text-slate-655 dark:text-zinc-400 uppercase tracking-widest mb-3 block">Quick Launch Preset Recordings:</span>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  {SAMPLES.map(s => (
                    <button key={s.title} type="button" onClick={() => handleSample(s)}
                      className="px-4 py-3 bg-surface dark:bg-zinc-900 border border-black/5 dark:border-white/10 text-left hover:border-accent-gold transition-all active:scale-95 flex items-center gap-3 group"
                    >
                      <span className="material-symbols-outlined text-accent-gold group-hover:scale-110 transition-transform" style={{ fontVariationSettings: "'FILL' 1" }}>volume_up</span>
                      <div className="overflow-hidden">
                        <p className="font-sans font-semibold text-xs text-primary dark:text-white truncate">{s.title}</p>
                        <span className="text-[9px] text-slate-450 dark:text-zinc-500 uppercase tracking-widest font-mono">{s.cat}</span>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <AnimatePresence>
              {runState === 'done' && generatedBrd && (
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                  className="p-6 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 flex flex-col sm:flex-row justify-between items-center gap-4"
                >
                  <div>
                    <h4 className="font-serif font-bold text-emerald-800 dark:text-emerald-400 text-sm italic flex items-center gap-2">
                      <span className="material-symbols-outlined text-md" style={{ fontVariationSettings: "'FILL' 1" }}>check_circle</span>
                      Requirements extraction ready — {projectName}
                    </h4>
                    <p className="text-xs text-slate-655 dark:text-zinc-400 mt-1 font-sans font-normal">
                      Compliance model compiled 8 distinct requirements. Ready to sync workspace.
                    </p>
                  </div>
                  <button onClick={handleCompile}
                    className="bg-emerald-700 hover:bg-emerald-800 text-white font-bold py-2.5 px-5 text-xs uppercase tracking-widest shadow-md transition-all active:scale-95 whitespace-nowrap cursor-pointer"
                  >
                    Compile &amp; Edit Draft ➜
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <div className="lg:col-span-4 flex flex-col bg-surface dark:bg-[#111111] border border-black/5 dark:border-white/10 shadow-sm overflow-hidden h-[540px] sticky top-20">
            <div className="bg-primary dark:bg-zinc-900 text-white p-5 flex items-center justify-between border-b border-primary/20 dark:border-white/10">
              <div className="flex items-center gap-3">
                <span className="material-symbols-outlined text-white/80 dark:text-accent-gold animate-pulse" style={{ fontVariationSettings: "'FILL' 1" }}>auto_awesome</span>
                <div>
                  <p className="font-sans font-semibold text-xs text-white">Genie Refinement Desk</p>
                  <span className="text-[9px] uppercase font-bold tracking-widest text-white/50 font-mono">Conversational Solver</span>
                </div>
              </div>
              <span className="text-[9px] bg-white/10 px-2 py-0.5 border border-white/20 text-white/70 font-bold uppercase font-mono">Live</span>
            </div>

            <div className="flex-1 p-5 overflow-y-auto space-y-5 bg-bg-cream dark:bg-black/40">
              {chat.map((m, i) => (
                <div key={i} className={`flex flex-col ${m.sender === 'user' ? 'items-end' : 'items-start'}`}>
                  <div className={`p-3.5 text-xs leading-relaxed max-w-[85%] ${
                    m.sender === 'user'
                      ? 'bg-primary dark:bg-accent-purple text-white shadow-sm rounded-2xl rounded-br-sm'
                      : 'bg-white dark:bg-zinc-800 text-primary dark:text-white border border-black/5 dark:border-white/5 shadow-sm font-sans font-normal rounded-2xl rounded-bl-sm'
                  }`}>
                    {m.text}
                  </div>
                  <span className="text-[9px] text-slate-450 dark:text-zinc-500 mt-1 px-1 font-mono">{m.time}</span>
                </div>
              ))}
            </div>

            <div className="p-4 bg-surface dark:bg-[#111111] border-t border-black/5 dark:border-white/10">
              <span className="text-[9px] font-bold text-slate-450 dark:text-zinc-500 uppercase tracking-widest block mb-2 font-mono">SUGGESTED RESPONSES</span>
              <div className="flex flex-col gap-1.5">
                {[
                  'Yes, enforce full RBAC with secure OAuth2 credentials.',
                  'Keep it simple — standard permissions for scope v1.',
                ].map(t => (
                  <button key={t} type="button" onClick={() => handleSendChat(t)}
                    className="bg-bg-cream dark:bg-zinc-900 hover:bg-white dark:hover:bg-zinc-800 text-primary dark:text-white border border-black/10 dark:border-white/10 px-3 py-1.5 text-xs font-semibold cursor-pointer text-left truncate font-sans font-semibold transition-colors rounded-lg"
                  >
                    "{t}"
                  </button>
                ))}
              </div>
            </div>

            <form onSubmit={e => { e.preventDefault(); handleSendChat(chatInput); }}
              className="p-4 bg-bg-cream dark:bg-zinc-900 border-t border-black/5 dark:border-white/10 flex items-center gap-3"
            >
              <input type="text" value={chatInput} onChange={e => setChatInput(e.target.value)}
                placeholder="Reply or add custom rules…"
                className="flex-1 bg-white dark:bg-zinc-800 border border-black/10 dark:border-white/10 focus:border-accent-gold px-3 py-2 text-xs outline-none text-primary dark:text-white font-sans rounded-xl transition-colors"
              />
              <button type="submit"
                className="h-9 w-9 bg-primary dark:bg-accent-gold text-white dark:text-black flex items-center justify-center hover:bg-neutral-800 cursor-pointer transition-transform active:scale-90 rounded-xl shrink-0"
              >
                <span className="material-symbols-outlined text-sm" style={{ fontVariationSettings: "'FILL' 1" }}>send</span>
              </button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
